new flag: --info-path returns the path to the info.json file
and guarantee silence only when using -x|--exists.

diff --git a/mameinfo b/mameinfo
--- a/mameinfo
+++ b/mameinfo
@@ -5,6 +5,7 @@
 # Usage: mameinfo [-d|--init-path] <rompath>
 #        mameinfo [-x|--exists] <rompath/rom.zip>
 #        mameinfo [jq options] [-g|--get,-l|--get-all] <rompath/rom.zip>
+#        mameinfo [--info-file] <rompath/rom.zip>
 # see oq --help
 #
 # requires standalone mame and oq.
@@ -18,7 +19,7 @@ then
 fi
 
 zparseopts -D -E - {d,-init-path}:=zinit_path \
-  {x,-exists,g,-get,l,-get-all}:=zrom_file || return 1
+  {x,-exists,g,-get,l,-get-all,-info-path}:=zrom_file || return 1
 
 if ! (( ${#zinit_path} + ${#zrom_file} ))
 then
@@ -26,6 +27,7 @@ then
 	Usage: mameinfo [-d|--init-path] <rompath>
 	       mameinfo [-x|--exists] <rompath/rom.zip>
 	       mameinfo [jq options] [-g|--get,-l|--get-all] <rompath/rom.zip>
+	       mameinfo [--info-file] <rompath/rom.zip>
 	see oq --help
 	EOF
   return 1
@@ -119,6 +121,13 @@ then
   fi
 fi
 
+# if you don't want this message, use --exists.
+if [[ $flag != (-x|--exists) && ! -f $info_file ]]
+then
+  echo "info missing for $rom_file:t" >&2
+  return 1
+fi
+
 case $flag in
   -x|--exists)
     return $( test -f $info_file )
@@ -128,5 +137,8 @@ case $flag in
     ;;
   -l|--get-all)
     oq ${@:-.} $info_file
+    ;;
+  --info-path)
+    echo $( realpath $info_file )
     ;;
 esac
