Updates!
- argument for a custom template.
- feedback & instructions when the core cannot be determined.
- copy over info settings from RetroArch so it inherits version and minimum OS version.
- update --help (basic).
- more readable code.

diff --git a/rashortcuts b/rashortcuts
--- a/rashortcuts
+++ b/rashortcuts
@@ -9,6 +9,7 @@ zparseopts -D -E -F - \
   -favorites=favorites \
   -history=playhistory \
   {p,-playlist}:=playlist \
+  {t,-template}:=template \
   {h,-help}=help || {
     print "see --help" >&2
     return 1
@@ -16,65 +17,77 @@ zparseopts -D -E -F - \
 
 if [[ -n $help ]]; then
 cat <<- --------
-HELP TEXT PLACEHOLDER!
-
-Last argument should point to the directory where the shortcut.app will be created.
-Defaults to the current working directory.
-
-will process without fzf select mode.
-  --process-all
-  --process-existing  This will only overwrite existing shortcuts.
+usage: rashortcuts [OPTION]... [OUTPUT]
 
 Playlists:
   --favorites
   --history
   -p, --playlist <path/to/playlist.lpl>
 
-If no playlist argument is passed, fzf will list all of your playlists.
+If a playlist is not provided, fzf will list them automatically.
+
+Process without fzf game selection.
+  --process-all           process all entries for a given playlist
+  --process-existing      re-process existing shortcuts for a given output path
+
+Last argument should point to the directory where the shortcut.app will be created.
+Defaults to the current working directory.
+
+Custom templates:
+  --template <path/to/template>
+
+An optional template for building shortcuts. It defaults to the folder named
+"template" located in the same directory as this script.
 
 --------
-  return
+return
 fi
+
+s.header(){ printf "\n\e[1;30m%s\e[0m\n" $@ }
+s.ok()    { printf "\e[0;32m%s\e[0m\n" $@ }
+s.warn()  { printf "\e[0;33m%s\e[0m\n" $@ }
+s.error() { printf "\e[0;31m%s\e[0m\n" $@ >&2 }
 
 output=${1:-.}
 
 app_support=~/Library/Application\ Support/RetroArch
-template=$0:h/template
+# Ensure the default template is located with this script.
+template=${template[-1]:-$(dirname `realpath $0`)/template}
 
-function s.header {
-  printf "\n\e[1;30m%s\e[0m\n" "${(j[ ])@}"
-}
-function s.error {
-  printf "\e[0;31m%s\e[0m\n" "${(j[ ])@}"
-}
-function s.ok {
-  printf "\e[0;32m%s\e[0m\n" "${(j[ ])@}"
-}
-function s.warn {
-  printf "\e[0;33m%s\e[0m\n" "${(j[ ])@}"
-}
+if [[ ! -d $template/Contents/MacOS ]]; then
+  s.error "Template does not exist or is not valid: $template"
+  return 1
+fi
 
 if [[ -n $playlist ]]; then
   playlist=$playlist[-1]
 elif [[ -n $favorites ]]; then
-  favorites=$(eval printf %s `awk -F= '/content_favorites_path/ {print $2}' $app_support/config/retroarch.cfg`)
+  favorites=$(eval printf %s $(
+    awk -F= '/content_favorites_path/ {print $2}' $app_support/config/retroarch.cfg
+  ))
   playlist=${favorites/#\~/$HOME}
 elif [[ -n $playhistory ]]; then
-  playhistory=$(eval printf %s `awk -F= '/content_history_path/ {print $2}' $app_support/config/retroarch.cfg`)
+  playhistory=$(eval printf %s $(
+    awk -F= '/content_history_path/ {print $2}' $app_support/config/retroarch.cfg
+  ))
   playlist=${playhistory/#\~/$HOME}
 else
-  playlistdir=$(eval printf %s `awk -F= '/playlist_directory/ {print $2}' $app_support/config/retroarch.cfg`)
-  select=`for lpl in ${playlistdir/#\~/$HOME}/*.lpl; do echo $lpl:t:r; done | fzf`
+  playlistdir=$(eval printf %s $(
+    awk -F= '/playlist_directory/ {print $2}' $app_support/config/retroarch.cfg
+  ))
+  select=$(
+    for lpl in ${playlistdir/#\~/$HOME}/*.lpl; do echo $lpl:t:r; done | fzf
+  )
   if [[ -n $select ]]; then
     playlist=${playlistdir/#\~/$HOME}/$select.lpl
   else
-    s.warn Nothing selected.
+    s.warn "Nothing selected."
     return
   fi
 fi
 
 if [[ ! -f $playlist ]]; then
-  s.error Playlist does not exist:$playlist
+  s.error "Playlist does not exist:\n- $playlist"
   return 1
 fi
 
@@ -92,13 +105,26 @@ cleanlist=$(
 if [[ -n ${process_all:-$process_existing} ]]; then
   working_indices=( `print $cleanlist | cut -f1` )
 else
-  working_indices=( `print $cleanlist | fzf --multi --delimiter='\t' --with-nth=2 | cut -f1` )
+  working_indices=(
+    `print $cleanlist | fzf --multi --delimiter='\t' --with-nth=2 | cut -f1`
+  )
 fi
 
 if [[ -z $working_indices ]]; then
-  s.warn Nothing to process.
+  s.warn "Nothing to process."
   return
 fi
+
+for _bid in com.libretro.dist.RetroArch libretro.RetroArch; do
+  _biddir=`mdfind kMDItemCFBundleIdentifier = $_bid`
+  if [[ -n $_biddir ]]; then
+    app_dir=$_biddir
+    app_info=$_biddir/Contents/Info.plist
+    app_ver=`plutil -extract CFBundleShortVersionString raw $app_info`
+    min_ver=`plutil -extract LSMinimumSystemVersion raw $app_info`
+    break
+  fi
+done
 
 default_cname=`jq -r ".default_core_name" $playlist`
 default_cpath=`jq -r ".default_core_path" $playlist`
@@ -115,19 +141,26 @@ for i in $working_indices; do
   # Make label file system safe.
   # - replace ':' with ','
   # - replace '/' with '-'.
-  shortcutapp=$output/${${label//:/,}//\//-}.app
+  shortcut_app=$output/${${label//:/,}//\//-}.app
 
-  if [[ -n $process_existing ]] && [[ ! -d $shortcutapp ]]; then
+  if [[ -n $process_existing ]] && [[ ! -d $shortcut_app ]]; then
     continue
   fi
 
-  s.header Creating \"$shortcutapp:t\"
+  s.header "Creating \"$shortcut_app:t\""
 
-  mkdir -p $shortcutapp
-  if ! cp -R $template/Contents $shortcutapp; then
-    s.error Could not create \"$shortcutapp:t\".
+  mkdir -p $shortcut_app
+  if ! cp -R $template/Contents $shortcut_app; then
+    s.error "Could not create \"$shortcut_app:t\"."
     continue
   fi
+
+  shortcut_info=$shortcut_app/Contents/info.plist
+  plutil -insert CFBundleDisplayName -string $label $shortcut_info
+  plutil -insert CFBundleShortVersionString -string $app_ver $shortcut_info
+  plutil -insert LSMinimumSystemVersion -string $min_ver $shortcut_info
+  # plutil -insert NSHumanReadableCopyright -string $copyright $shortcut_info
+  # plutil -insert LSEnvironment -string $env_vars $shortcut_info
 
   # gpathextended: full path including possible archive content.
   # gpath: game path without the archive content pointers.
@@ -149,7 +182,7 @@ for i in $working_indices; do
   )
 
   # For each name in $thumbnames:
-  # - Chop off each occurance of `(.*)` from the trailing end.
+  # - Chop off each occurance of `(.*)` or `[.*]` from the trailing end.
   # - Add each iteration to the list of naming candidates.
   for _name in $thumbnames; do
     while [[ $_name =~ "^(.+)(\(|\[)([^([]*)(\)|\]).*$" ]]; do
@@ -160,7 +193,7 @@ for i in $working_indices; do
   done
 
   thumbfound=0
-  icnpath=$shortcutapp/Contents/Resources/shortcut.icns
+  icnpath=$shortcut_app/Contents/Resources/AppIcon.icns
   for set in Boxarts Titles Snaps; do
     for thumb in $thumbnames; do
       # Mimic RetroArch's safe naming for thumbnails.
@@ -169,7 +202,7 @@ for i in $working_indices; do
       if [[ -f $thumbpath ]]; then
         thumbfound=1
         s.ok "$set/$thumb.png -> $icnpath:t"
-        makeicns -in $thumbpath -out $icnpath
+        makeicns -align bottom -in $thumbpath -out $icnpath
         break 2
       fi
     done
@@ -180,7 +213,7 @@ for i in $working_indices; do
     fallback=$app_support/assets/xmb/retrosystem/png/$system-content.png
     if [[ -f $fallback ]]; then
       s.ok "retrosystem/$system-content.png -> $icnpath:t"
-      makeicns -in $fallback -out $icnpath
+      makeicns -align bottom -in $fallback -out $icnpath
     else
       s.warn Using the default $icnpath:t file.
     fi
@@ -194,32 +227,38 @@ for i in $working_indices; do
   # Limit application bundle id to alphanumerics.
   bundleid=libretro.RetroArch
   for s in $scname $fname; bundleid+=.`printf %s $s | tr -cd '[:alnum:]'`
-  if [[ -n $scname ]] && plutil -replace CFBundleIdentifier -xml $bundleid $shortcutapp/Contents/info.plist; then
-    s.ok BundleID: $bundleid
+  if [[ -n $scname ]] && \
+      plutil -replace CFBundleIdentifier -string $bundleid $shortcut_info
+  then
+    s.ok "BundleID: $bundleid"
   else
-    s.error BundleID not set.
+    s.error "BundleID not set."
   fi
 
   runnable=0
   if [[ -f $gpath ]]; then
-    sed -i '' -E "s:#GAME#:$gpathextended:" $shortcutapp/Contents/MacOS/launcher
-    s.ok game: $gpathextended:t
+    sed -i '' -E "s:#GAME#:$gpathextended:" $shortcut_app/Contents/MacOS/launcher && \
+      s.ok "game: $gpathextended:t"
 
     # Use simplified naming instead of fragile paths.
     if [[ -n $scname ]]; then
-      sed -i '' -E "s:#CORE#:$scname:" $shortcutapp/Contents/MacOS/launcher
-      s.ok core: $cname
-      runnable=1
+      sed -i '' -E "s:#CORE#:$scname:" $shortcut_app/Contents/MacOS/launcher && \
+        s.ok "core: $cname" && \
+        runnable=1
+    else
+      s.error "The core could not be determined from the playlist. Do one of the following:"
+      s.error "- Set a default core for the playlist. (recommended)"
+      s.error "- Run the game in RetroArch at least once from the playlist."
     fi
   fi
 
   if ! (( $runnable )); then
-    s.error Error assigning game path or core id.
+    s.error "Error assigning game path or core id."
     continue
   fi
 
-  chmod +x $shortcutapp/Contents/MacOS/launcher
+  chmod +x $shortcut_app/Contents/MacOS/launcher
 
-  codesign --force --sign - $shortcutapp
+  codesign --force --sign - $shortcut_app
 
 done
